feat(lap-624): speaking instruction and test mic
Lapin-Learn/main-website pull request #26
Opened 2024-12-25 07:35 UTC by MinEn1712

- Instructions carousel
- Mic checking

### Not done
- Play back the audio
- Mock skillTestId and session data to render Speaking page (for now to render Speaking Page you have to comment the code the requires the session data :"))

2024-12-25 10:41 UTC, NganTrucLe requested changes
Build fail á, còn lại t k hiểu cách uncomment để test local.
VD k cấp quyền micro nó có bật popup k 
![image](https://github.com/user-attachments/assets/ad0f4325-865f-4113-ae7e-0519a8380058)

2024-12-25 10:41 UTC, NganTrucLe commented on src/assets/icons/skills/microphone-filled.tsx
ms để ý cái icon speaking cũng là microphone, lấy lại hem

2024-12-25 10:41 UTC, NganTrucLe commented on src/components/pages/simulated-test/speaking.tsx
> +            {isListening && <AudioRipple audioLevel={audioLevel} />}
chắc đổi thành isRecording cho dễ hiểu

2024-12-26 11:20 UTC, MinEn1712 commented on src/assets/icons/skills/microphone-filled.tsx
cái micro đó là cái m chê é ẹc ẹc ☠️ nên t mới thêm cái nì vô :)) còn cái của lucide react ko hiểu s fill nó bị lỗi :")))

2024-12-26 13:47 UTC, NganTrucLe commented on src/assets/icons/skills/microphone-filled.tsx
à k k, chắc m nhầm á, ý là có chê nhma chê do nó outline hoi, lấy bản speaking filled là đc nhe

2024-12-27 11:59 UTC, MinEn1712 commented on src/assets/icons/skills/microphone-filled.tsx
à nì là cái microphone bữa m kiu đổi é :c

2024-12-29 05:32 UTC, NganTrucLe requested changes
Pull lại giúp t nha hic hic sr

2024-12-29 05:32 UTC, NganTrucLe commented on src/components/ui/audioRipple.tsx
ụa, sao đặt tên file lạ v :vvv

2024-12-29 05:32 UTC, NganTrucLe commented on src/lib/consts.ts
sr sr 🙏🏻 do t merge của t trc nên có conflict chỗ này sửa giùm t nha, có gì đổi biết là SPEAKING_TITLES vs SPEAKING_INSTRUCTIONS lun he, cái bên writing t cũng ms để 1 cái instructions nữa é :">

2024-12-29 05:32 UTC, NganTrucLe commented on src/hooks/zustand/use-recording-store.ts
> +  audio: null,
có thể để như này gọn hơn nè:
```
const initialState: SpeakingState = {
testState: "not-started",
  permission: false,
  stream: null,
  recordingStatus: "inactive",
  audioChunks: [],
  audio: null,
}

export const useSpeakingStore = create... ({
...initialState,
reset: () => set(initialState)
})
```

2024-12-29 05:32 UTC, NganTrucLe commented on src/hooks/zustand/use-recording-store.ts
> +export type TestState = "not-started" | "in-progress" | "finished";
t nhớ là có sẵn enum cho mí cái test rùi á m

2024-12-29 05:32 UTC, NganTrucLe commented on src/components/organisms/audio-progress.tsx
này thấy để molecules đc rùi :v

2024-12-29 05:36 UTC, NganTrucLe commented on src/hooks/zustand/use-recording-store.ts
> +export type TestState = "not-started" | "in-progress" | "finished";
![Uploading image.png…]()

2024-12-29 05:36 UTC, NganTrucLe commented on src/hooks/zustand/use-recording-store.ts
> +export type TestState = "not-started" | "in-progress" | "finished";
![image](https://github.com/user-attachments/assets/91a9d687-a0ad-40d8-905a-f64995f9130a)

2024-12-29 07:37 UTC, NganTrucLe approved these changes

2024-12-29 07:37 UTC, merged