feat(LAP-558): mock test config popup
Lapin-Learn/main-website pull request #6
Opened 2024-12-09 11:31 UTC by MinEn1712

- Mock test configuration popup
- Mulitple select

2024-12-09 12:30 UTC, NganTrucLe requested changes

2024-12-09 12:30 UTC, NganTrucLe commented on src/components/mocules/form-inputs/form-multiple-select.tsx
> +              placeholder="Chọn phần bài muốn làm"
I18n

2024-12-09 12:30 UTC, NganTrucLe commented on src/components/organisms/select-mode-dialog.tsx
> +  { value: "10", label: "10 phút" },
I18n, dưới dạng "{{minutes}} phút"

2024-12-09 12:30 UTC, NganTrucLe commented on src/components/organisms/select-mode-dialog.tsx
> +              title="Chế độ luyện tập"
I18n

2024-12-09 12:30 UTC, NganTrucLe commented on src/components/organisms/select-mode-dialog.tsx
> +                  label="Thời gian"
I18n lun nha

2024-12-09 12:30 UTC, NganTrucLe commented on src/components/pages/practice.tsx
> +// const listeningSections = [
Tách ra thành file mock.ts

2024-12-09 12:30 UTC, NganTrucLe commented on src/components/ui/multi-select.tsx
Cái này copy code từ bên select à :))) sao m k làm cái prop isMulti á, tại logic như nhau chỉ khác cái onChange thôi, trả về array hoặc là single item

2024-12-09 17:38 UTC, NganTrucLe requested changes
![image](https://github.com/user-attachments/assets/aa77ad65-e4fa-4c79-9e1e-fec04cbb8dba)
Đổi mào ik bà, nhạt thôi :">>> với lại cái placeholder k có cần để badge phức tạp v đâu, m vẫn để string xong join là được, kiểu "Phần 1, phần 2, phần 3" đó :v, là mấy cái label join lại hoi
Nhớ sửa lại đừng dùng command nha, chưa cần search luôn á, đơn giản thôi 💀 . Chắc bỏ cái cancel clear gì lun nha

2024-12-10 08:55 UTC, NganTrucLe requested changes

2024-12-10 08:55 UTC, NganTrucLe commented on src/components/organisms/select-mode-dialog.tsx
> +                  </div>
Là mode practice không có icon hả :">>

2024-12-11 05:33 UTC, vmathu approved these changes

2024-12-11 16:56 UTC, merged